export const TRAINING_DATA = [
  ["hello", "Hello! How can I help you?"],
  ["hi", "Hi! What would you like to know?"],
  ["hey", "Hey! What can I help you with?"],
  ["what is your name", "My name is Himo."],
  ["who are you", "I am Himo, your AI assistant."],
  ["how are you", "I am doing well. How can I help?"],
  ["what can you do", "I can answer questions, explain concepts, write code and help debug problems."],
  ["help me with coding", "Sure. Send me the code and explain what you want to build."],
  ["fix my bug", "Send me the error and relevant code. I will analyze the problem and suggest a fix."],
  ["what is javascript", "JavaScript is a programming language commonly used to build interactive applications."],
  ["what is an api", "An API lets different software components communicate with each other."],
  ["thank you", "You're welcome!"],
  ["good morning", "Good morning! How can I help today?"],
  ["good night", "Good night!"],
  ["bye", "Bye! Talk to you later."],
]
